### PR TITLE
Cmssw 7 6 x

### PR DESCRIPTION
**Pull request by tmitchel**
Hi Devdatta,
Here is the branch that has all of the fixes that we made to 76X that need to be propogated to 80X. My version of OS2LAna.cc is a bit messy, but it has all of the important changes. I can try to clean it up and send you another merge request soon, if you would like.

### CODE REVIEW

**Comment by dmajumder** [comment]
Hi Tyler, sorry this PR cannot be merged. There are way too many files changed.
Please modify this, or make a new PR with changes only to:
- the OS2LAna class (cleaned up) and its config;
  There should in principle be no need to change any other file except for bug fixes. In that case, please tell me the bugs you fixed.

No root, text file, condor/ batch/ CRAB submission scripts etc. should go into the PR. Thanks.

**Comment by tmitchel** [comment]
Hi Devdatta, is it complaining about anything specific or just the whole thing? Because from my side it says that my branch doesn't have any conflicts with yours

**Comment by dmajumder** [comment]
No the complaint is from my side :-) certain files should never be on github, like I said before, and only the analysis class and related configs should require change. so a lot of cleanup to do still. I suggest you do this on a separate branch on your local copy and then we can look at it.

**Comment by tmitchel** [comment]
Ahh i see haha. I'm working on a branch called cleanup that I've pushed to github so we can look at it. I deleted all of the text files I could find and all of the root files (don't know how they got there, I have *.root in my .gitignore)
As for the config files, I only have bash scripts I included to make producing configs easier in the Condor directories. Should I remove these files before we merge as well?

**Comment by dmajumder** [comment]
you can keep all scripts etc locally, just that they should not be on the repo.

**Pull request closed without merging**
