### PR TITLE
Cmssw 8 0 x new b2 g ana fw

### PR DESCRIPTION
**Pull request by skhalil**
I only made changes to

a)  README.md 
b) python/OS2LAna_cfi.py 
c) test/inputFiles_cfi.py 
d) test/os2lana_cfg.py 

I don't know why the rest are appearing, but I did compare each of them to your CMSSW_8_0_X_NewB2GAnaFW branch and they are same.

### CODE REVIEW

**Review by dmajumder — CHANGES_REQUESTED** [review]
@skhalil looking at the code I think it is better to have the z pt cut from the test/os2lana_cfg file directly. I updated it. In principle there is no other change needed for this cut, so I am closing the PR.

Once you have the histograms in the OS2LAna.cc please update this PR (remember to do git pull from my branch before modifying). I will merge the changes with the histo. Please do not update any other files.

**Comment by skhalil** [comment]
I agree that Z pt should be controlled from cfg file. However, I have added sys options of _cfi.py file and have largely modified OS2LAna.cc. I have commented out lot of useless histograms and computation that has not been used by either Tyler and Rachitha in 1.5 years. I will send you a PR.

**Comment by dmajumder** [comment]
@skhalil PR merged and closed

**Comment by skhalil** [comment]
you forgot to copy these root files: https://github.com/dmajumder/VLQAna/blob/CMSSW_8_0_X_NewB2GAnaFW/test/os2lana_cfg.py#L133-L136 from my git. Why should I delete my local repo? I plan to use it for any other developments.

**Comment by dmajumder** [comment]
@skhalil done ("PUDistMC_2016_25ns_SpringMC_PUScenarioV1_PoissonOOTPU.root" was already added.)

**Pull request merged**
